"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
type Department={id:string;name:string;code:string;_count:{programmes:number;courses:number;students:number;staff:number}};
type Faculty={id:string;name:string;code:string;departments:Department[];_count:{departments:number;staff:number}};
export default function FacultyAdministration(){
 const [faculties,setFaculties]=useState<Faculty[]>([]),[facultyName,setFacultyName]=useState(""),[facultyCode,setFacultyCode]=useState(""),[deptName,setDeptName]=useState(""),[deptCode,setDeptCode]=useState(""),[facultyId,setFacultyId]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
 async function load(){const r=await fetch("/api/admin/academics",{cache:"no-store"}),d=await r.json();if(r.ok){setFaculties(d);if(!facultyId&&d[0])setFacultyId(d[0].id)}else setError(d.error||"Unable to load academic units.")}
 useEffect(()=>{void load()},[]);
 async function post(payload:Record<string,string>){setError("");setMessage("");setLoading(true);try{const r=await fetch("/api/admin/academics",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok){setError(d.error||"Request failed.");return}setMessage("Academic unit saved.");await load()}finally{setLoading(false)}}
 function createFaculty(e:FormEvent){e.preventDefault();void post({action:"create-faculty",name:facultyName,code:facultyCode});setFacultyName("");setFacultyCode("")}
 function createDept(e:FormEvent){e.preventDefault();void post({action:"create-department",facultyId,name:deptName,code:deptCode});setDeptName("");setDeptCode("")}
 return <main className="portalPage"><nav className="portalNav"><Link href="/admin" className="brand"><span className="brandMark">U</span><span>Academic units</span></Link><Link href="/api/auth/logout" className="portalLogout">Sign out</Link></nav><section className="portalHero"><div className="eyebrow">ACADEMIC STRUCTURE</div><h1>Faculties & departments</h1><p>Manage the institutional hierarchy used by programmes, courses, students and staff.</p></section><section className="registrationShell"><div className="adminGrid"><article className="portalCard"><h3>Create faculty</h3><form className="adminForm" onSubmit={createFaculty}><label>Faculty name<input value={facultyName} onChange={e=>setFacultyName(e.target.value)} required/></label><label>Code<input value={facultyCode} onChange={e=>setFacultyCode(e.target.value)} placeholder="SCI" required/></label><button className="primary" disabled={loading}>Create faculty</button></form></article><article className="portalCard"><h3>Create department</h3><form className="adminForm" onSubmit={createDept}><label>Faculty<select value={facultyId} onChange={e=>setFacultyId(e.target.value)} required>{faculties.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Department name<input value={deptName} onChange={e=>setDeptName(e.target.value)} required/></label><label>Code<input value={deptCode} onChange={e=>setDeptCode(e.target.value)} placeholder="CSC" required/></label><button className="primary" disabled={loading||!faculties.length}>Create department</button></form></article></div>{error&&<div className="formError">{error}</div>}{message&&<div className="successBox">{message}</div>}<div className="catalogList">{faculties.map(f=><article className="portalCard" key={f.id}><div className="registrationHeader"><div><div className="eyebrow">FACULTY · {f.code}</div><h3>{f.name}</h3><p>{f._count.departments} departments · {f._count.staff} staff</p></div></div><div className="catalogList">{f.departments.map(d=><div className="catalogRow" key={d.id}><b>{d.code}</b><div><strong>{d.name}</strong><span>{d._count.programmes} programmes · {d._count.courses} courses · {d._count.students} students · {d._count.staff} staff</span></div></div>)}{!f.departments.length&&<div className="emptyState">No departments yet.</div>}</div></article>)}</div></section></main>
}
